/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd_practica1_201313692;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.xml.sax.*;
import org.w3c.dom.*;
import javax.xml.parsers.*;




/**
 *
 * @author jossie
 */
public class inicio extends javax.swing.JFrame {
    EDD_Practica1_201313692 test=new EDD_Practica1_201313692();
     int TamañoMatriz;
    String player="";
    int jugadores=0;
    
    
      juego ventana2=new juego();

    
    
    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
         
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(600, 400));

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("LEER ARCHIVO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("JUGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //fileChooser ventana2=new fileChooser();
       // ventana2.setVisible(true);
          jDialog1.setVisible(true);       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
File archivoSeleccionado;
    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
       FileNameExtensionFilter filtro = new FileNameExtensionFilter("txt","txt");
        int resultado;
        JFileChooser selectorArchivo=(JFileChooser)evt.getSource();
        String command=evt.getActionCommand();
        String texto="";
        String proyecto="";
        if(command.equals(JFileChooser.APPROVE_SELECTION)){
            archivoSeleccionado=selectorArchivo.getSelectedFile();
            FileReader fr=null;
            //System.out.println(archivoSeleccionado.toString());
//            JOptionPane.showMessageDialog(this, "Ruta:"+archivoSeleccionado.getAbsolutePath()+
//                    "\n Archivo:"+archivoSeleccionado.getName());
            try{
                  fr=new FileReader(archivoSeleccionado.toString());
                  BufferedReader entrada=new BufferedReader(fr);
                  String cadena=entrada.readLine();
                  while(cadena!=null){
                      //System.out.println(cadena);
                      texto=cadena+"\n";
                      proyecto=proyecto+texto;
                      cadena=entrada.readLine();
                      
                  }
                  //System.out.println("#########################################");
                  //System.out.println(proyecto);
           
               System.out.println(proyecto);
               //String path="\""+archivoSeleccionado.toString()+"\"";
               //System.out.println(path);
               carga(archivoSeleccionado.toString());
        }catch(Exception ex){

           
            JOptionPane.showMessageDialog(null, "Error abriendo la el archivo "+ ex);
                 
        }
          
            
        }else if(command.equals(JFileChooser.CANCEL_SELECTION)){
            JOptionPane.showMessageDialog(this, "selecciona un archivo...");
        }

        
        
        
               
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //selecciono una cantidad de jugadores para la partida
        jugadores=Integer.parseInt(JOptionPane.showInputDialog("Cantidad de Jugadores"));
        //ingreso los X jugadores nombre por nombre
        
        for(int x=0;x<jugadores;x++){
            player=JOptionPane.showInputDialog("Ingrese Nombre de Jugador");
            System.out.println("player "+(x+1)+": "+player);
            test.listacircular.Insertar(x, player,0);
          
        }
        
        //NodoListaFichas pieza1 =new NodoListaFichas();
       
        
        for(int x=0;x<jugadores;x++){
            if(x==0){
                for(int y=0;y<7;y++){
                    NodoListaFichas pieza =new NodoListaFichas();
                    pieza.setFicha(test.colaFicha.buscar(0).getFicha());
                    pieza.setValor(test.colaFicha.buscar(0).getValor());
                    test.listaF.push(pieza);
                    test.colaFicha.eliminar(0);
                }
            }else if(x==1){
                for(int y=0;y<7;y++){
                    NodoListaFichas pieza =new NodoListaFichas();
                    pieza.setFicha(test.colaFicha.buscar(0).getFicha());
                    pieza.setValor(test.colaFicha.buscar(0).getValor());
                    test.listaF1.push(pieza);
                    test.colaFicha.eliminar(0);
                }
            }else if(x==2){
                for(int y=0;y<7;y++){
                    NodoListaFichas pieza =new NodoListaFichas();
                    pieza.setFicha(test.colaFicha.buscar(0).getFicha());
                    pieza.setValor(test.colaFicha.buscar(0).getValor());
                    test.listaF2.push(pieza);
                    test.colaFicha.eliminar(0);
                }
            }else if(x==3){
                for(int y=0;y<7;y++){
                    NodoListaFichas pieza =new NodoListaFichas();
                    pieza.setFicha(test.colaFicha.buscar(0).getFicha());
                    pieza.setValor(test.colaFicha.buscar(0).getValor());
                    test.listaF3.push(pieza);
                    test.colaFicha.eliminar(0);
                }
            }else if(x==4){
                for(int y=0;y<7;y++){
                    NodoListaFichas pieza =new NodoListaFichas();
                    pieza.setFicha(test.colaFicha.buscar(0).getFicha());
                    pieza.setValor(test.colaFicha.buscar(0).getValor());
                    test.listaF4.push(pieza);
                    test.colaFicha.eliminar(0);
                }
            }else if(x==5){
                for(int y=0;y<7;y++){
                    NodoListaFichas pieza =new NodoListaFichas();
                    pieza.setFicha(test.colaFicha.buscar(0).getFicha());
                    pieza.setValor(test.colaFicha.buscar(0).getValor());
                    test.listaF5.push(pieza);
                    test.colaFicha.eliminar(0);
                }
            }else if(x==6){
                for(int y=0;y<7;y++){
                    NodoListaFichas pieza =new NodoListaFichas();
                    pieza.setFicha(test.colaFicha.buscar(0).getFicha());
                    pieza.setValor(test.colaFicha.buscar(0).getValor());
                    test.listaF6.push(pieza);
                    test.colaFicha.eliminar(0);
                }
            }else if(x==7){
                for(int y=0;y<7;y++){
                    NodoListaFichas pieza =new NodoListaFichas();
                    pieza.setFicha(test.colaFicha.buscar(0).getFicha());
                    pieza.setValor(test.colaFicha.buscar(0).getValor());
                    test.listaF7.push(pieza);
                    test.colaFicha.eliminar(0);
                }
            }else if(x==8){
                for(int y=0;y<7;y++){
                    NodoListaFichas pieza =new NodoListaFichas();
                    pieza.setFicha(test.colaFicha.buscar(0).getFicha());
                    pieza.setValor(test.colaFicha.buscar(0).getValor());
                    test.listaF8.push(pieza);
                    test.colaFicha.eliminar(0);
                }
            }
        }
        
        
        
        
      // test.listacircular.MostrarLista();
//       for(int x=0;x<test.listacircular.)
System.out.println("########################33");
      // System.out.println(test.listacircular.Recorrido());
       
     
       ventana2.setVisible(true);
      dispose();
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    public void carga(String ruta){
        
        try {
            File inputFile=new File(ruta);
            DocumentBuilderFactory dbFactory= DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder=dbFactory.newDocumentBuilder();
            Document doc=dBuilder.parse(inputFile);
            doc.getDocumentElement().normalize();
            System.out.println("raiz: "+doc.getDocumentElement().getNodeName());
            NodeList tamaño=doc.getElementsByTagName("scrabble");
                 for(int temp=0;temp<tamaño.getLength();temp++){
                Node nNode =tamaño.item(temp);
                System.out.println("\nActual: "+nNode.getNodeName());
                if(nNode.getNodeType()==Node.ELEMENT_NODE){
                    Element eElement=(Element) nNode;
                    String dimension=eElement.getElementsByTagName("dimension").item(0).getTextContent();
                    //System.out.println("tamaño del arreglo: "+eElement.getElementsByTagName("dimension").item(0).getTextContent());
                        TamañoMatriz=Integer.parseInt(dimension);
                        System.out.println("tamaño de la matriz: "+TamañoMatriz);
                        ventana2.TamañoMatriz=TamañoMatriz;
                }
            
            
            }    
            
            //para cargar las casillas dobles
            NodeList doble=doc.getElementsByTagName("casillas");
            System.out.println("----------------------------");
           // System.out.println(nList.getLength());
            for(int temp=0;temp<doble.getLength();temp++){
                Node nNode =doble.item(temp);
                System.out.println("\nActual: "+nNode.getNodeName());
                
                if(nNode.getNodeType()==Node.ELEMENT_NODE){
                    Element eElement=(Element) nNode;
                    String a=eElement.getElementsByTagName("x").item(0).getTextContent();
                    String b=eElement.getElementsByTagName("y").item(0).getTextContent();
                    test.matriz.Insertar(Integer.parseInt(a), Integer.parseInt(b), 3,"DOBLE");
                    System.out.println("casilla X: "+a+" casilla Y: "+b);
                    
                }
            
            
            }
           
            //para cargar las casillas triples
             NodeList triple=doc.getElementsByTagName("casilla");
            System.out.println("----------------------------");
           // System.out.println(nList.getLength());
            for(int temp=0;temp<triple.getLength();temp++){
                Node nNode =triple.item(temp);
                System.out.println("\nActual: "+nNode.getNodeName());
                
                if(nNode.getNodeType()==Node.ELEMENT_NODE){
                    Element eElement=(Element) nNode;
                    String a=eElement.getElementsByTagName("x").item(0).getTextContent();
                    String b=eElement.getElementsByTagName("y").item(0).getTextContent();
                    test.matriz.Insertar(Integer.parseInt(a), Integer.parseInt(b), 3,"TRIPLE");
                    System.out.println("casilla X: "+a+" casilla Y: "+b);
                }
            
            
            }
            
            
            //para cargar todas las palabras del diccionario del XML
            NodeList diccionario=doc.getElementsByTagName("palabra");
            System.out.println("----------------------------");
           // System.out.println(nList.getLength());
           System.out.println("diccionario");
            for(int temp=0;temp<diccionario.getLength();temp++){
                Node nNode =diccionario.item(temp);
               // System.out.println("\n actual: "+nNode.getNodeName());
                NodoListaDiccionario palabra1 =new NodoListaDiccionario();
                if(nNode.getNodeType()==Node.ELEMENT_NODE){
                    Element eElement=(Element) nNode;
                    //System.out.println("palabra: "+eElement.getElementsByTagName("palabra").item(0).getTextContent());
                    //System.out.println(eElement.getChildNodes().item(0).getTextContent());
                     String pal1 =eElement.getChildNodes().item(0).getTextContent();
                     palabra1.setPalabra(pal1);
                    test.listaD.push(palabra1);
                }
            
            
            }
            test.matriz.llenar(TamañoMatriz, TamañoMatriz);
            for(int y=0;y<test.listaD.size();y++){
            System.out.println("palabra "+y+1+": "+test.listaD.buscar(y).getPalabra());
        }
            
        }catch(Exception e) {
            e.printStackTrace();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables

   
}
